### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by praeludiumOrbis** [upgradeQ/OSU-STREAM-DETECTOR#2] opened 2020-08-01 20:04 UTC
Happens on "ANiMA [Soul]", can't link the beatmap as my osu! database is fucked up for whatever reason.

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "e:\program files\python\python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "e:\program files\python\python39\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "e:\program files\python\python39\lib\site-packages\is_it_stream.py", line 57, in _check
    raw_map = open(of, "r", encoding="utf8").readlines()
  File "e:\program files\python\python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 849: invalid continuation byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\program files\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\program files\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Program Files\Python\Python39\Scripts\osustreams.exe\__main__.py", line 7, in <module>
  File "e:\program files\python\python39\lib\site-packages\is_it_stream.py", line 328, in main
    audios = pool.map(_check, of)
  File "e:\program files\python\python39\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "e:\program files\python\python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 849: invalid continuation byte
```

**Comment by upgradeQ** [comment] 2020-08-02 16:56
Hi @myangelaku ,thanks for reporting , but  I cannot reproduce the error , is it right beatmap - https://bloodcat.com/osu/?q=624995&c=s ?  
It is possible now  to ignore the errors while parsing files , just provide `-i` ignore flag.  
Otherwise it will skip those files.  
 Update to latest version with `python -m pip install -U osustreams`

**Comment by zvbt** [comment] 2020-10-15 10:30
Hi, i have an error on this map https://osu.ppy.sh/beatmapsets/952101#fruits/1988172 but is osu!catch
would it be possible to detect that the map osu std?

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\v7_th\appdata\local\programs\python\python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\v7_th\appdata\local\programs\python\python39\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "c:\users\v7_th\appdata\local\programs\python\python39\lib\site-packages\is_it_stream.py", line 69, in _check
    if raw_map[0] != "osu file format v14\n":
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\v7_th\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\v7_th\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\v7_th\AppData\Local\Programs\Python\Python39\Scripts\osustreams.exe\__main__.py", line 7, in <module>
  File "c:\users\v7_th\appdata\local\programs\python\python39\lib\site-packages\is_it_stream.py", line 342, in main
    audios = pool.map(_check, of)
  File "c:\users\v7_th\appdata\local\programs\python\python39\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\users\v7_th\appdata\local\programs\python\python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
IndexError: list index out of range

**Comment by upgradeQ** [comment] 2020-10-16 03:21
Hello @zvbt Yes, it is possible, according to https://osu.ppy.sh/help/wiki/osu!_File_Formats/Osu_(file_format) if we look for line with `[Mode]` and if it equals 0, then it is osu! std map. The new  version 1.1.0  :package: is accounting for it. 

Update `python -m pip install -U osustreams`
As for traceback above, it is better to test new version, then open new issue if it breaks again.

**Comment by upgradeQ** [comment] 2020-11-09 05:20
Closing, as with version `1.1.1` it will skip problematic files.

**Closed as completed by upgradeQ** 2020-11-09 05:20 UTC
